<template>
  <div class="contenedor-principal">
    <div class="contenedor-cabecero">
      <div class="contenedor-intro">
        <h1>Geobizi</h1>
        <h2>A la caza de las plantas</h2>
        <h3>Selecciona las plantas que ves en tu camino</h3>
      </div>
    </div>

    <div class="contenedor-medio">
      <div>
        <h2>¿Cuáles de estas plantas identificas?</h2>
        <h3>Seleccionalas y al final de la ruta envía el resultado para descubrir algunos datos</h3>

        <div class="plants-button">
          <div class="contenedor-plantas-imagenes">
            <div v-for="plant in selectedPlants" :key="plant.id">
              <router-link :to="'/plantas/' + plant.id">
                <PlantCard class="fitxa" :plant="plant"/>
              </router-link>
            </div>
          </div>
          <button @click="enviar">Resultados</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import PlantCard from '../components/PlantCard.vue';
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';


const router = useRouter();

const allPlants = ref([
  {
    "campos": true,
    "caracteristic": "prados",
    "costa": false,
    "description": "El diente de león es una planta herbácea de la familia de las asteráceas. Se encuentra en prados y campos abiertos, siendo común en primavera.",
    "descriptionEnvironment": "Se encuentra en prados y campos abiertos, siendo común en primavera.",
    "exotic": false,
    "id": 1,
    "image": "/imagenes/plantas/diente-de-leon.png",
    "interior": false,
    "invasive": false,
    "jardines": false,
    "montaña": false,
    "native": true,
    "otros": false,
    "prados": true,
    "rowid": 1,
    "soil": "arcilloso",
    "title": "Diente de León"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La margarita es una planta herbácea perenne de la familia de las asteráceas. Tiene flores blancas y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene flores blancas y se utiliza en jardinería y ornamentación.",
    "exotic": true,
    "id": 2,
    "image": "/imagenes/plantas/margarita.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 2,
    "soil": "arcilloso",
    "title": "Margarita"
  },
  {
    "campos": true,
    "caracteristic": "textil",
    "costa": false,
    "description": "El lino es una planta herbácea anual de la familia de las lináceas. Se cultiva por sus fibras, que se utilizan en la industria textil.",
    "descriptionEnvironment": "Se cultiva por sus fibras, que se utilizan en la industria textil.",
    "exotic": false,
    "id": 3,
    "image": "/imagenes/plantas/lino.png",
    "interior": false,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 3,
    "soil": "arcilloso",
    "title": "Lino"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La malva es una planta herbácea perenne de la familia de las malváceas. Tiene flores rosadas y se utiliza en jardinería y medicina tradicional.",
    "descriptionEnvironment": "Tiene flores rosadas y se utiliza en jardinería y medicina tradicional.",
    "exotic": true,
    "id": 4,
    "image": "/imagenes/plantas/malva.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 4,
    "soil": "arcilloso",
    "title": "Malva"
  },
  {
    "campos": true,
    "caracteristic": "alimentación",
    "costa": false,
    "description": "La achicoria es una planta herbácea bienal de la familia de las asteráceas. Se cultiva por sus hojas, que se utilizan en alimentación humana.",
    "descriptionEnvironment": "Se cultiva por sus hojas, que se utilizan en alimentación humana.",
    "exotic": false,
    "id": 5,
    "image": "/imagenes/plantas/achicoria.png",
    "interior": false,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 5,
    "soil": "arcilloso",
    "title": "Achicoria"
  },
  {
    "campos": false,
    "caracteristic": "medicinal",
    "costa": false,
    "description": "La zarzaparrilla es una planta trepadora de la familia de las smiláceas. Tiene propiedades medicinales y se utiliza en la medicina tradicional.",
    "descriptionEnvironment": "Tiene propiedades medicinales y se utiliza en la medicina tradicional.",
    "exotic": true,
    "id": 6,
    "image": "/imagenes/plantas/zarzaparrilla.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 6,
    "soil": "arcilloso",
    "title": "Zarzaparrilla"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La madreselva es una planta trepadora de la familia de las caprifoliáceas. Tiene flores fragantes y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene flores fragantes y se utiliza en jardinería y ornamentación.",
    "exotic": true,
    "id": 7,
    "image": "/imagenes/plantas/madreselva.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 7,
    "soil": "arcilloso",
    "title": "Madreselva"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "El tamarix es un arbusto o árbol de la familia de las tamaricáceas. Tiene flores rosadas y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene flores rosadas y se utiliza en jardinería y ornamentación.",
    "exotic": true,
    "id": 8,
    "image": "/imagenes/plantas/tamarix.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 8,
    "soil": "arcilloso",
    "title": "Tamarix"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "El pino de Monterrey es un árbol de la familia de las pináceas. Tiene hojas perennes en forma de aguja y se utiliza en jardinería y forestación.",
    "descriptionEnvironment": "Tiene hojas perennes en forma de aguja y se utiliza en jardinería y forestación.",
    "exotic": true,
    "id": 9,
    "image": "/imagenes/plantas/pino-de-monterrey.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 9,
    "soil": "arcilloso",
    "title": "Pino de Monterrey"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "El plumero pampeano es una planta herbácea perenne de la familia de las asteráceas. Tiene flores rosadas y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene flores rosadas y se utiliza en jardinería y ornamentación.",
    "exotic": true,
    "id": 10,
    "image": "/imagenes/plantas/plumero-pampeano.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 10,
    "soil": "arcilloso",
    "title": "Plumero Pampeano"
  },
  {
    "campos": false,
    "caracteristic": "medicinal",
    "costa": false,
    "description": "La uña de gato es una planta trepadora de la familia de las rubiáceas. Tiene propiedades medicinales y se utiliza en la medicina tradicional.",
    "descriptionEnvironment": "Tiene propiedades medicinales y se utiliza en la medicina tradicional.",
    "exotic": true,
    "id": 11,
    "image": "/imagenes/plantas/una-de-gato.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 11,
    "soil": "arcilloso",
    "title": "Uña de Gato"
  },
  {
    "campos": true,
    "caracteristic": "medicinal",
    "costa": false,
    "description": "La valeriana roja es una planta herbácea perenne de la familia de las valerianáceas. Tiene propiedades medicinales y se utiliza en la medicina tradicional.",
    "descriptionEnvironment": "Tiene propiedades medicinales y se utiliza en la medicina tradicional.",
    "exotic": true,
    "id": 12,
    "image": "/imagenes/plantas/valeriana-roja.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 12,
    "soil": "arcilloso",
    "title": "Valeriana Roja"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La vinca pervinca es una planta herbácea perenne de la familia de las apocináceas. Tiene flores azules o violetas y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene flores azules o violetas y se utiliza en jardinería y ornamentación.",
    "exotic": true,
    "id": 13,
    "image": "/imagenes/plantas/vinca-pervinca.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 13,
    "soil": "arcilloso",
    "title": "Vinca Pervinca"
  },
  {
    "campos": true,
    "caracteristic": "alimentación",
    "costa": false,
    "description": "La cerraja es una planta herbácea anual de la familia de las asteráceas. Se cultiva por sus hojas, que se utilizan en alimentación humana.",
    "descriptionEnvironment": "Se cultiva por sus hojas, que se utilizan en alimentación humana.",
    "exotic": false,
    "id": 14,
    "image": "/imagenes/plantas/cerraja.png",
    "interior": false,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 14,
    "soil": "arcilloso",
    "title": "Cerraja"
  },
  {
    "campos": true,
    "caracteristic": "alimentación",
    "costa": false,
    "description": "El rábano silvestre es una planta herbácea anual de la familia de las brassicáceas. Se cultiva por su raíz, que se utiliza en alimentación humana.",
    "descriptionEnvironment": "Se cultiva por su raíz, que se utiliza en alimentación humana.",
    "exotic": false,
    "id": 15,
    "image": "/imagenes/plantas/rabano-silvestre.png",
    "interior": false,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 15,
    "soil": "arcilloso",
    "title": "Rábano Silvestre"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La argoma es una planta arbustiva de la familia de las fabáceas. Se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Se utiliza en jardinería y ornamentación.",
    "exotic": false,
    "id": 16,
    "image": "/imagenes/plantas/argoma.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 16,
    "soil": "arcilloso",
    "title": "Argoma"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "El brezo es un arbusto de la familia de las ericáceas. Tiene flores rosadas y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene flores rosadas y se utiliza en jardinería y ornamentación.",
    "exotic": false,
    "id": 17,
    "image": "/imagenes/plantas/brezo.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 17,
    "soil": "arcilloso",
    "title": "Brezo"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "El trébol morado es una planta herbácea perenne de la familia de las fabáceas. Se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Se utiliza en jardinería y ornamentación.",
    "exotic": false,
    "id": 18,
    "image": "/imagenes/plantas/trebol-morado.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 18,
    "soil": "arcilloso",
    "title": "Trébol Morado"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La pulmonaria es una planta herbácea perenne de la familia de las boragináceas. Tiene flores rosadas o azules y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene flores rosadas o azules y se utiliza en jardinería y ornamentación.",
    "exotic": false,
    "id": 19,
    "image": "/imagenes/plantas/pulmonaria.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 19,
    "soil": "arcilloso",
    "title": "Pulmonaria"
  },
  {
    "campos": false,
    "caracteristic": "madera",
    "costa": false,
    "description": "El roble es un árbol caducifolio de la familia de las fagáceas. Se utiliza en carpintería y ebanistería por su madera resistente.",
    "descriptionEnvironment": "Se utiliza en carpintería y ebanistería por su madera resistente.",
    "exotic": false,
    "id": 20,
    "image": "/imagenes/plantas/roble.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 20,
    "soil": "arcilloso",
    "title": "Roble"
  },
  {
    "campos": false,
    "caracteristic": "madera",
    "costa": false,
    "description": "La haya es un árbol caducifolio de la familia de las fagáceas. Se utiliza en carpintería y ebanistería por su madera dura.",
    "descriptionEnvironment": "Se utiliza en carpintería y ebanistería por su madera dura.",
    "exotic": false,
    "id": 21,
    "image": "/imagenes/plantas/haya.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 21,
    "soil": "arcilloso",
    "title": "Haya"
  },
  {
    "campos": true,
    "caracteristic": "gin",
    "costa": true,
    "description": "El enebro es un arbusto perenne de la familia de las cupresáceas. Tiene frutos comestibles y se utiliza en la elaboración de gin.",
    "descriptionEnvironment": "Tiene frutos comestibles y se utiliza en la elaboración de gin.",
    "exotic": false,
    "id": 22,
    "image": "/imagenes/plantas/enebro.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 22,
    "soil": "arenoso",
    "title": "Enebro"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "El tilo es un árbol caducifolio de la familia de las tiliáceas. Tiene flores fragantes y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene flores fragantes y se utiliza en jardinería y ornamentación.",
    "exotic": false,
    "id": 23,
    "image": "/imagenes/plantas/tilo.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": true,
    "rowid": 23,
    "soil": "arcilloso",
    "title": "Tilo"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "El acebo es un arbusto perenne de la familia de las aquifoliáceas. Tiene bayas rojas y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene bayas rojas y se utiliza en jardinería y ornamentación.",
    "exotic": false,
    "id": 24,
    "image": "/imagenes/plantas/acebo.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": true,
    "rowid": 24,
    "soil": "arcilloso",
    "title": "Acebo"
  },
  {
    "campos": true,
    "caracteristic": "perfumería",
    "costa": true,
    "description": "La lavanda es un arbusto aromático de la familia de las lamiáceas. Tiene flores moradas y se utiliza en perfumería y cosmé__tica.",
    "descriptionEnvironment": "Tiene flores moradas y se utiliza en perfumería y cosmé__tica.",
    "exotic": true,
    "id": 25,
    "image": "/imagenes/plantas/lavanda.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 25,
    "soil": "arenoso",
    "title": "Lavanda"
  },
  {
    "campos": true,
    "caracteristic": "cocina",
    "costa": true,
    "description": "El romero es un arbusto aromático de la familia de las lamiáceas. Tiene hojas aromáticas y se utiliza en la cocina y la medicina tradicional.",
    "descriptionEnvironment": "Tiene hojas aromáticas y se utiliza en la cocina y la medicina tradicional.",
    "exotic": true,
    "id": 26,
    "image": "/imagenes/plantas/romero.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 26,
    "soil": "arenoso",
    "title": "Romero"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "El helecho es una planta ornamental de la familia de las pteridáceas. Tiene hojas verdes y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene hojas verdes y se utiliza en jardinería y ornamentación.",
    "exotic": false,
    "id": 27,
    "image": "/imagenes/plantas/helecho.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 27,
    "soil": "arcilloso",
    "title": "Helecho"
  },
  {
    "campos": true,
    "caracteristic": "alimentación",
    "costa": false,
    "description": "La alcachofa es una planta herbácea perenne de la familia de las asteráceas. Se cultiva por sus cabezas florales, que se utilizan en alimentación humana.",
    "descriptionEnvironment": "Se cultiva por sus cabezas florales, que se utilizan en alimentación humana.",
    "exotic": false,
    "id": 28,
    "image": "/imagenes/plantas/alcachofa.png",
    "interior": false,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 28,
    "soil": "arcilloso",
    "title": "Alcachofa"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La clemátide es una planta trepadora de la familia de las ranunculáceas. Tiene flores llamativas y se utiliza en jardinería y ornamentación.",
    "descriptionEnvironment": "Tiene flores llamativas y se utiliza en jardinería y ornamentación.",
    "exotic": false,
    "id": 29,
    "image": "/imagenes/plantas/clematide.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 29,
    "soil": "arcilloso",
    "title": "Clemátide"
  },
  {
    "campos": true,
    "caracteristic": "fitoterapia",
    "costa": true,
    "description": "La Hierba de San Juan es una planta herbácea de la familia de las hipericáceas. Tiene propiedades medicinales y se utiliza en fitoterapia.",
    "descriptionEnvironment": "Tiene propiedades medicinales y se utiliza en fitoterapia.",
    "exotic": false,
    "id": 30,
    "image": "/imagenes/plantas/hierba-de-san-juan.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": true,
    "rowid": 30,
    "soil": "arenoso",
    "title": "Hierba de San Juan"
  },
  {
    "campos": true,
    "caracteristic": "gastronomía",
    "costa": true,
    "description": "El perejil gigante es una hierba aromática de la familia Apiaceae. Tiene hojas grandes y se utiliza en gastronomía y medicina.",
    "descriptionEnvironment": "Tiene hojas grandes y se utiliza en gastronomía y medicina.",
    "exotic": false,
    "id": 31,
    "image": "/imagenes/plantas/perejil-gigante.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 31,
    "soil": "arcilloso",
    "title": "Perejil Gigante"
  },
  {
    "campos": true,
    "caracteristic": "gastronomía",
    "costa": true,
    "description": "La menta es una planta aromática de la familia de las lamiáceas. Tiene hojas fragantes y se utiliza en gastronomía, perfumería y medicina.",
    "descriptionEnvironment": "Tiene hojas fragantes y se utiliza en gastronomía, perfumería y medicina.",
    "exotic": false,
    "id": 32,
    "image": "/imagenes/plantas/menta.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 32,
    "soil": "arcilloso",
    "title": "Menta"
  },
  {
    "campos": true,
    "caracteristic": "gastronomía",
    "costa": true,
    "description": "La hierbabuena es una planta aromática de la familia de las lamiáceas. Tiene hojas aromáticas y se utiliza en gastronomía y medicina.",
    "descriptionEnvironment": "Tiene hojas aromáticas y se utiliza en gastronomía y medicina.",
    "exotic": false,
    "id": 33,
    "image": "/imagenes/plantas/hierbabuena.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 33,
    "soil": "arcilloso",
    "title": "Hierbabuena"
  },
  {
    "campos": true,
    "caracteristic": "carpintería",
    "costa": true,
    "description": "El pino silvestre es un árbol perenne de la familia de las pináceas. Tiene hojas aciculares y se utiliza en carpintería y ebanistería.",
    "descriptionEnvironment": "Tiene hojas aciculares y se utiliza en carpintería y ebanistería.",
    "exotic": false,
    "id": 34,
    "image": "/imagenes/plantas/pino-silvestre.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 34,
    "soil": "arenoso",
    "title": "Pino Silvestre"
  },
  {
    "campos": true,
    "caracteristic": "medicina",
    "costa": true,
    "description": "El llanté__n es una planta herbácea de la familia de las plantagináceas. Tiene hojas lanceoladas y se utiliza en medicina tradicional.",
    "descriptionEnvironment": "Tiene hojas lanceoladas y se utiliza en medicina tradicional.",
    "exotic": false,
    "id": 35,
    "image": "/imagenes/plantas/llanten.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 35,
    "soil": "arcilloso",
    "title": "Llanté__n"
  },
  {
    "campos": true,
    "caracteristic": "fitoterapia",
    "costa": false,
    "description": "El cardo es una planta herbácea de la familia de las asteráceas. Tiene propiedades medicinales y se utiliza en fitoterapia.",
    "descriptionEnvironment": "Tiene propiedades medicinales y se utiliza en fitoterapia.",
    "exotic": false,
    "id": 36,
    "image": "/imagenes/plantas/cardo.png",
    "interior": false,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 36,
    "soil": "arcilloso",
    "title": "Cardo"
  },
  {
    "campos": true,
    "caracteristic": "gastronomía",
    "costa": true,
    "description": "El saúco es un arbusto perenne de la familia de las adoxáceas. Tiene flores blancas y se utiliza en gastronomía y medicina tradicional.",
    "descriptionEnvironment": "Tiene flores blancas y se utiliza en gastronomía y medicina tradicional.",
    "exotic": false,
    "id": 37,
    "image": "/imagenes/plantas/sauco.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 37,
    "soil": "arcilloso",
    "title": "Saúco"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": false,
    "description": "El tulipán es una planta bulbosa de la familia de las liliáceas. Tiene flores llamativas y se utiliza en jardinería y floricultura.",
    "descriptionEnvironment": "Tiene flores llamativas y se utiliza en jardinería y floricultura.",
    "exotic": true,
    "id": 38,
    "image": "/imagenes/plantas/tulipan.png",
    "interior": false,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 38,
    "soil": "arcilloso",
    "title": "Tulipán"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": false,
    "description": "La magnolia es un árbol perenne de la familia de las magnoliáceas. Tiene flores grandes y vistosas y se utiliza en jardinería y paisajismo.",
    "descriptionEnvironment": "Tiene flores grandes y vistosas y se utiliza en jardinería y paisajismo.",
    "exotic": true,
    "id": 39,
    "image": "/imagenes/plantas/magnolia.png",
    "interior": false,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 39,
    "soil": "arcilloso",
    "title": "Magnolia"
  },
  {
    "campos": true,
    "caracteristic": "carpintería",
    "costa": true,
    "description": "El fresno es un árbol caducifolio de la familia de las oleáceas. Tiene hojas compuestas y se utiliza en carpintería y ebanistería.",
    "descriptionEnvironment": "Tiene hojas compuestas y se utiliza en carpintería y ebanistería.",
    "exotic": false,
    "id": 40,
    "image": "/imagenes/plantas/fresno.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 40,
    "soil": "arcilloso",
    "title": "Fresno"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": false,
    "description": "El ficus es un árbol perenne de la familia de las moráceas. Tiene hojas grandes y se utiliza en jardinería y decoración interior.",
    "descriptionEnvironment": "Tiene hojas grandes y se utiliza en jardinería y decoración interior.",
    "exotic": true,
    "id": 41,
    "image": "/imagenes/plantas/ficus.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 41,
    "soil": "arcilloso",
    "title": "Ficus"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": false,
    "description": "El cactus es una planta suculenta de la familia de las cactáceas. Tiene tallos carnosos y se utiliza en jardinería y decoración.",
    "descriptionEnvironment": "Tiene tallos carnosos y se utiliza en jardinería y decoración.",
    "exotic": true,
    "id": 42,
    "image": "/imagenes/plantas/cactus.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 42,
    "soil": "arenoso",
    "title": "Cactus"
  },
  {
    "campos": true,
    "caracteristic": "carpintería",
    "costa": true,
    "description": "El eucalipto es un árbol perenne de la familia de las mirtáceas. Tiene hojas lanceoladas y se utiliza en carpintería y medicina.",
    "descriptionEnvironment": "Tiene hojas lanceoladas y se utiliza en carpintería y medicina.",
    "exotic": true,
    "id": 43,
    "image": "/imagenes/plantas/eucalipto.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 43,
    "soil": "arenoso",
    "title": "Eucalipto"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "El ciprés es un árbol perenne de la familia de las cupresáceas. Tiene hojas escamosas y se utiliza en jardinería y paisajismo.",
    "descriptionEnvironment": "Tiene hojas escamosas y se utiliza en jardinería y paisajismo.",
    "exotic": false,
    "id": 44,
    "image": "/imagenes/plantas/cipres.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 44,
    "soil": "arenoso",
    "title": "Ciprés"
  },
  {
    "campos": false,
    "caracteristic": "construcción",
    "costa": true,
    "description": "El bambú es una planta leñosa de la familia de las poáceas. Tiene tallos largos y flexibles y se utiliza en construcción y artesanía.",
    "descriptionEnvironment": "Tiene tallos largos y flexibles y se utiliza en construcción y artesanía.",
    "exotic": true,
    "id": 45,
    "image": "/imagenes/plantas/bambu.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 45,
    "soil": "arenoso",
    "title": "Bambú"
  },
  {
    "campos": true,
    "caracteristic": "construcción",
    "costa": true,
    "description": "La caña es una planta herbácea de la familia de las poáceas. Tiene tallos huecos y se utiliza en construcción y artesanía.",
    "descriptionEnvironment": "Tiene tallos huecos y se utiliza en construcción y artesanía.",
    "exotic": false,
    "id": 46,
    "image": "/imagenes/plantas/cana.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 46,
    "soil": "arcilloso",
    "title": "Caña"
  },
  {
    "campos": true,
    "caracteristic": "gastronomía",
    "costa": true,
    "description": "El laurel es un arbusto perenne de la familia de las lauráceas. Tiene hojas lanceoladas y se utiliza en gastronomía y medicina.",
    "descriptionEnvironment": "Tiene hojas lanceoladas y se utiliza en gastronomía y medicina.",
    "exotic": false,
    "id": 47,
    "image": "/imagenes/plantas/laurel.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 47,
    "soil": "arcilloso",
    "title": "Laurel"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": false,
    "description": "La begonia es una planta ornamental de la familia de las begoniáceas. Tiene flores llamativas y se utiliza en jardinería y decoración interior.",
    "descriptionEnvironment": "Tiene flores llamativas y se utiliza en jardinería y decoración interior.",
    "exotic": true,
    "id": 48,
    "image": "/imagenes/plantas/begonia.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 48,
    "soil": "arcilloso",
    "title": "Begonia"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": false,
    "description": "La orquídea es una planta epífita de la familia de las orquidáceas. Tiene flores exóticas y se utiliza en jardinería y floristería.",
    "descriptionEnvironment": "Tiene flores exóticas y se utiliza en jardinería y floristería.",
    "exotic": true,
    "id": 49,
    "image": "/imagenes/plantas/orquidea.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 49,
    "soil": "arcilloso",
    "title": "Orquídea"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La Tradescantia fluminensis es una planta perenne de la familia Commelinaceae. Tiene hojas verdes y se utiliza en jardinería y paisajismo.",
    "descriptionEnvironment": "Tiene hojas verdes y se utiliza en jardinería y paisajismo.",
    "exotic": true,
    "id": 50,
    "image": "/imagenes/plantas/tradescantia-fluminensis.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 50,
    "soil": "arcilloso",
    "title": "Tradescantia Fluminensis"
  },
  {
    "campos": true,
    "caracteristic": "gastronomía",
    "costa": true,
    "description": "El tomillo es un arbusto aromático de la familia de las lamiáceas. Tiene hojas pequeñas y se utiliza en gastronomía y medicina.",
    "descriptionEnvironment": "Tiene hojas pequeñas y se utiliza en gastronomía y medicina.",
    "exotic": false,
    "id": 51,
    "image": "/imagenes/plantas/tomillo.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 51,
    "soil": "arcilloso",
    "title": "Tomillo"
  },
  {
    "campos": true,
    "caracteristic": "agricultura",
    "costa": false,
    "description": "El almendro es un árbol caducifolio de la familia de las rosáceas. Tiene frutos comestibles y se utiliza en agricultura y repostería.",
    "descriptionEnvironment": "Tiene frutos comestibles y se utiliza en agricultura y repostería.",
    "exotic": false,
    "id": 52,
    "image": "/imagenes/plantas/almendro.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 52,
    "soil": "arcilloso",
    "title": "Almendro"
  },
  {
    "campos": true,
    "caracteristic": "carpintería",
    "costa": false,
    "description": "El nogal es un árbol caducifolio de la familia de las juglandáceas. Tiene frutos comestibles y se utiliza en carpintería y alimentación.",
    "descriptionEnvironment": "Tiene frutos comestibles y se utiliza en carpintería y alimentación.",
    "exotic": false,
    "id": 53,
    "image": "/imagenes/plantas/nogal.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 53,
    "soil": "arcilloso",
    "title": "Nogal"
  },
  {
    "campos": true,
    "caracteristic": "carpintería",
    "costa": true,
    "description": "El cedro es un árbol perenne de la familia de las pináceas. Tiene madera aromática y se utiliza en carpintería y construcción.",
    "descriptionEnvironment": "Tiene madera aromática y se utiliza en carpintería y construcción.",
    "exotic": true,
    "id": 54,
    "image": "/imagenes/plantas/cedro.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 54,
    "soil": "arcilloso",
    "title": "Cedro"
  },
  {
    "campos": true,
    "caracteristic": "carpintería",
    "costa": true,
    "description": "El abeto es un árbol perenne de la familia de las pináceas. Tiene hojas aciculares y se utiliza en carpintería y decoración.",
    "descriptionEnvironment": "Tiene hojas aciculares y se utiliza en carpintería y decoración.",
    "exotic": true,
    "id": 55,
    "image": "/imagenes/plantas/abeto.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 55,
    "soil": "arcilloso",
    "title": "Abeto"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": false,
    "description": "El narciso es una planta bulbosa de la familia de las amarilidáceas. Tiene flores perfumadas y se utiliza en jardinería y floristería.",
    "descriptionEnvironment": "Tiene flores perfumadas y se utiliza en jardinería y floristería.",
    "exotic": false,
    "id": 56,
    "image": "/imagenes/plantas/narciso.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 56,
    "soil": "arcilloso",
    "title": "Narciso"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La hiedra es una planta trepadora de la familia de las araliáceas. Tiene hojas perennes y se utiliza en jardinería y paisajismo.",
    "descriptionEnvironment": "Tiene hojas perennes y se utiliza en jardinería y paisajismo.",
    "exotic": false,
    "id": 57,
    "image": "/imagenes/plantas/hiedra.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 57,
    "soil": "arcilloso",
    "title": "Hiedra"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": false,
    "description": "La violeta es una planta herbácea de la familia de las violáceas. Tiene flores coloridas y se utiliza en jardinería y perfumería.",
    "descriptionEnvironment": "Tiene flores coloridas y se utiliza en jardinería y perfumería.",
    "exotic": false,
    "id": 58,
    "image": "/imagenes/plantas/violeta.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 58,
    "soil": "arcilloso",
    "title": "Violeta"
  },
  {
    "campos": true,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La amapola es una planta herbácea de la familia de las papaveráceas. Tiene flores vistosas y se utiliza en jardinería y medicina.",
    "descriptionEnvironment": "Tiene flores vistosas y se utiliza en jardinería y medicina.",
    "exotic": false,
    "id": 59,
    "image": "/imagenes/plantas/amapola.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 59,
    "soil": "arcilloso",
    "title": "Amapola"
  },
  {
    "campos": true,
    "caracteristic": "ganadería",
    "costa": false,
    "description": "La encina es un árbol perenne de la familia de las fagáceas. Tiene hojas coriáceas y se utiliza en ganadería y leña.",
    "descriptionEnvironment": "Tiene hojas coriáceas y se utiliza en ganadería y leña.",
    "exotic": false,
    "id": 60,
    "image": "/imagenes/plantas/encina.png",
    "interior": true,
    "invasive": false,
    "jardines": false,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 60,
    "soil": "arcilloso",
    "title": "Encina"
  },
  {
    "campos": true,
    "caracteristic": "medicina",
    "costa": true,
    "description": "La ortiga es una planta herbácea de la familia de las urticáceas. Tiene hojas urticantes y se utiliza en medicina y alimentación.",
    "descriptionEnvironment": "Tiene hojas urticantes y se utiliza en medicina y alimentación.",
    "exotic": false,
    "id": 61,
    "image": "/imagenes/plantas/ortiga.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": true,
    "rowid": 61,
    "soil": "arcilloso",
    "title": "Ortiga"
  },
  {
    "campos": true,
    "caracteristic": "gastronomía",
    "costa": true,
    "description": "El hinojo silvestre es una planta herbácea de la familia de las apiáceas. Tiene hojas aromáticas y se utiliza en gastronomía y medicina.",
    "descriptionEnvironment": "Tiene hojas aromáticas y se utiliza en gastronomía y medicina.",
    "exotic": false,
    "id": 62,
    "image": "/imagenes/plantas/hinojo-silvestre.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": true,
    "rowid": 62,
    "soil": "arcilloso",
    "title": "Hinojo Silvestre"
  },
  {
    "campos": true,
    "caracteristic": "agricultura",
    "costa": false,
    "description": "La cebada es una planta herbácea de la familia de las poáceas. Tiene granos comestibles y se utiliza en agricultura y alimentación.",
    "descriptionEnvironment": "Tiene granos comestibles y se utiliza en agricultura y alimentación.",
    "exotic": false,
    "id": 63,
    "image": "/imagenes/plantas/cebada.png",
    "interior": true,
    "invasive": false,
    "jardines": false,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 63,
    "soil": "arcilloso",
    "title": "Cebada"
  },
  {
    "campos": true,
    "caracteristic": "agricultura",
    "costa": false,
    "description": "La avena es una planta herbácea de la familia de las poáceas. Tiene granos comestibles y se utiliza en agricultura y alimentación.",
    "descriptionEnvironment": "Tiene granos comestibles y se utiliza en agricultura y alimentación.",
    "exotic": false,
    "id": 64,
    "image": "/imagenes/plantas/avena.png",
    "interior": true,
    "invasive": false,
    "jardines": false,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 64,
    "soil": "arcilloso",
    "title": "Avena"
  },
  {
    "campos": false,
    "caracteristic": "gastronomía",
    "costa": true,
    "description": "El hinojo de mar es una planta acuática de la familia de las apiáceas. Tiene hojas aromáticas y se utiliza en gastronomía y medicina.",
    "descriptionEnvironment": "Tiene hojas aromáticas y se utiliza en gastronomía y medicina.",
    "exotic": false,
    "id": 65,
    "image": "/imagenes/plantas/hinojo-mar.png",
    "interior": false,
    "invasive": false,
    "jardines": false,
    "montaña": false,
    "native": true,
    "otros": false,
    "prados": false,
    "rowid": 65,
    "soil": "arcilloso",
    "title": "Hinojo de Mar"
  },
  {
    "campos": true,
    "caracteristic": "medicina",
    "costa": true,
    "description": "La cola de caballo es una planta herbácea de la familia de las equisetáceas. Tiene tallos estriados y se utiliza en medicina y jardinería.",
    "descriptionEnvironment": "Tiene tallos estriados y se utiliza en medicina y jardinería.",
    "exotic": false,
    "id": 66,
    "image": "/imagenes/plantas/cola-caballo.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": true,
    "otros": false,
    "prados": true,
    "rowid": 66,
    "soil": "arcilloso",
    "title": "Cola de Caballo"
  },
  {
    "campos": true,
    "caracteristic": "agricultura",
    "costa": false,
    "description": "La alfalfa es una planta herbácea de la familia de las fabáceas. Tiene hojas trifoliadas y se utiliza en agricultura y alimentación animal.",
    "descriptionEnvironment": "Tiene hojas trifoliadas y se utiliza en agricultura y alimentación animal.",
    "exotic": false,
    "id": 67,
    "image": "/imagenes/plantas/alfalfa.png",
    "interior": true,
    "invasive": false,
    "jardines": false,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 67,
    "soil": "arcilloso",
    "title": "Alfalfa"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": false,
    "description": "La Fallopia japonica es una planta perenne invasora de la familia Polygonaceae. Tiene hojas grandes y se utiliza en jardinería y medicina alternativa.",
    "descriptionEnvironment": "Tiene hojas grandes y se utiliza en jardinería y medicina alternativa.",
    "exotic": false,
    "id": 68,
    "image": "/imagenes/plantas/fallopia-japonica.png",
    "interior": true,
    "invasive": true,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 68,
    "soil": "arcilloso",
    "title": "Fallopia Japonica"
  },
  {
    "campos": false,
    "caracteristic": "jardinería",
    "costa": true,
    "description": "La Cotula coronopifolia es una planta herbácea de la familia Asteraceae. Tiene hojas pequeñas y se utiliza en jardinería y paisajismo.",
    "descriptionEnvironment": "Tiene hojas pequeñas y se utiliza en jardinería y paisajismo.",
    "exotic": true,
    "id": 69,
    "image": "/imagenes/plantas/cotula-coronopifolia.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": false,
    "native": false,
    "otros": false,
    "prados": false,
    "rowid": 69,
    "soil": "arcilloso",
    "title": "Cotula Coronopifolia"
  },
  {
    "campos": true,
    "caracteristic": "medicina",
    "costa": true,
    "description": "La caléndula es una planta herbácea de la familia de las asteráceas. Tiene flores de color anaranjado y se utiliza en medicina y jardinería.",
    "descriptionEnvironment": "Tiene flores de color anaranjado y se utiliza en medicina y jardinería.",
    "exotic": false,
    "id": 70,
    "image": "/imagenes/plantas/calendula.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 70,
    "soil": "arcilloso",
    "title": "Caléndula"
  },
  {
    "campos": true,
    "caracteristic": "agricultura",
    "costa": true,
    "description": "El trébol blanco es una planta herbácea de la familia de las fabáceas. Tiene flores blancas y se utiliza en agricultura y jardinería.",
    "descriptionEnvironment": "Tiene flores blancas y se utiliza en agricultura y jardinería.",
    "exotic": false,
    "id": 71,
    "image": "/imagenes/plantas/trebol-blanco.png",
    "interior": true,
    "invasive": false,
    "jardines": true,
    "montaña": true,
    "native": false,
    "otros": false,
    "prados": true,
    "rowid": 71,
    "soil": "arcilloso",
    "title": "Trébol Blanco"
  }
]);



const selectedPlants = ref([]);

const getRandomPlants = () => {
  const randomPlants = [];
  const totalPlants = allPlants.value.length;
  const numberOfPlantsToShow = 10;
  const selectedIndices = new Set();

  // Genera 10 índices aleatorios únicos
  while (selectedIndices.size < numberOfPlantsToShow) {
    const randomIndex = Math.floor(Math.random() * totalPlants);
    selectedIndices.add(randomIndex);
  }

  // Agrega las plantas correspondientes a los índices aleatorios generados
  selectedIndices.forEach(index => {
    randomPlants.push(allPlants.value[index]);
  });

  return randomPlants;
};

const loadSelectedPlantsFromLocalStorage = () => {
  const storedPlants = JSON.parse(localStorage.getItem('selectedPlants'));
  if (storedPlants) {
    selectedPlants.value = storedPlants;
  } else {
    selectedPlants.value = getRandomPlants();
    localStorage.setItem('selectedPlants', JSON.stringify(selectedPlants.value));
  }
};

onMounted(() => {
  loadSelectedPlantsFromLocalStorage();
});

const enviar = () => {

  router.push('/result');
/*   results(); */
};
</script>



<style scoped>
h1 {
  color: #498536;
}
.contenedor-principal {
  padding-top: 7rem;
  background-color: rgb(255, 255, 255);
  padding-bottom: 2rem;
}
.contenedor-cabecero {
  padding: 5rem;
  background-image: url('/public/imagenes/background/10.png');
  background-size: cover; 
  background-position: center; 
  background-color: rgb(44, 119, 15); 
}
.contenedor-intro {
  max-width: 40rem;
  padding: 2rem;
  background-color: white;
}
.contenedor-medio {
  padding: 2rem;

}
.contenedor-plantas-imagenes{
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
}
.plants-button {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
button {
    padding: 0.7rem 1.2rem;
    margin: 0.5rem;
    border-radius: 0.5rem;
    background-color: #498536;
    border: solid 0.15rem rgb(27, 73, 8);
    color: white;
    font-size: large;
    transition: 250ms ease;
}
button:hover {
    background-color: rgb(27, 73, 8); 
    color:  #26B12C; 
    cursor: pointer;
}
</style>